### ISSUE TITLE
Can You Please explain how to load a pbix file to an SSAS server 

### ISSUE THREAD

**Issue by djouallah** [akavalar/SSAS-on-a-shoestring#1]
questions

does this instance of "personal" SSAS works from the network.
is it possible to load a pbix file instead of a powerpivot model.

thank you very much

**Comment by djouallah** [comment]
just tried it and it works perfectly, i have a ssas running in my personal computer :)

**Comment by akavalar** [comment]
Hm, not exactly sure what pbix files are. I found a couple of them here: http://bit.ly/2gtnvCZ and when I looked at Gantt.pbix it seemed like it's just a ZIP archive. There's an abf file inside the archive, it's called DataModel (note: no extension). If you modify one line of my code (replace 'if ".data" in member:' with if '"DataModel" in member:'), you can load these pbix files into your SSAS server and query them without modifying anything else. For example, I ran "EVALUATE Table1" and it worked just fine.

**Comment by djouallah** [comment]
thanks a lot
