### ISSUE TITLE
Just a little more, please

### ISSUE THREAD

**Issue by hugovanier** [akavalar/SSAS-on-a-shoestring#2]
Hi akavalar
Thanks a lot for your Project, that's amazing.

I trying (until few days) to add access to another user (In the same domain).

Would you have a tips for me?

**Comment by hugovanier** [comment]
Hi akavalar

I found the solution a few weeks ago:

1. Configure your firewall for let's release data on the 2383 port, or simply your ip address.

2. Add this code at the end of the "restorePowerPivot" function.

#create a new role
role = db.Roles.Add("Role_My user");

#If already created
role = db.Roles[0];

#Link new role to a domain user
role.Members.Add(AMO.RoleMember("[Domain name]\[user]"));
role.Update();
    
#Assign administrative permissions to this role.
#Members of this role can perform any operation within the database.
dbperm = db.DatabasePermissions.Add(role.ID);

**Comment by akavalar** [comment]
Awesome @hugovanier, I've added this to the write-up. Thanks!
